### ISSUE TITLE
r3 as standalone dependency

### ISSUE THREAD

**Issue by brendanashworth** [c9s/r3#76]
Hi there,

I'm intending to use r3 as a dependency in my project, but I don't want to force it upon end users to install it globally for `#include <r3.h>` (or any other dependencies, such as PCRE). Do you have any advice for making it a standalone dependency?

Thanks.

**Comment by c9s** [comment]
Hi, I think you can use cmake submodule. but I am not sure.

**Comment by brendanashworth** [comment]
okay. thank you!
