### ISSUE TITLE
PHP extension for R3

### ISSUE THREAD

**Issue by Gasol** [c9s/r3#78]
I plan to work with PHP extension in a couple of weeks.

I think we should separate r3 and r3-php into two repository in the future, But for the sake of API stability We are still committing the changes into single repository.

**Comment by c9s** [comment]
Few notes:

- [ ] Make static linking r3 with php extension works.
- [ ] Add a persistent C structure that maintains a pointer to the built tree structure of r3.
- [ ] Make the basic API `R3::create` works.
- [ ] Test cases

**Comment by c9s** [comment]
Done in c9s/php-r3
