### ISSUE TITLE
Can't match root uri "/"

### ISSUE THREAD

**Issue by coney** [c9s/r3#85]
It's ok to insert a new route for "/".

but when I try to match uri "/", r3 told me that nothing matched.

**Comment by c9s** [comment]
Could you call `r3_tree_dump` and paste the dumped tree structure ? Thanks

**Comment by c9s** [comment]
Please see 5f39b7321124f98a369110c7f0922c6cd0db11bd I added a test case for it, and it passes

**Comment by coney** [comment]
I have sent a pull request for this case: https://github.com/c9s/r3/pull/86

the root uri "/" will fail if it was added by `r3_tree_insert_route`

`check_tree.c:738:F:testcase:test_insert_route:0: Assertion 'r != ((void*)0)' failed`

**Comment by c9s** [comment]
Fixed
