### ISSUE TITLE
Error with configure.ac

### ISSUE THREAD

**Issue by mjs6643** [c9s/r3#96]
When I run ./configure I get the following error:

> ./configure: line 17189: syntax error near unexpected token `have_check="no"'
> ./configure: line 17189:`$as_echo "$as_me: WARNING: Check not found; cannot run unit tests!" >&2;} have_check="no"'

**Comment by yohanboniface** [comment]
Guilty commit is https://github.com/c9s/r3/commit/0ba956159cc06e259ca7a08f074d8ee958f11c7f

Checking out the commit before (5a644ee04686715ae65343cf69a1d5854b9e4e0f) is a workaround.
